name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: hexo
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Setup hexo
        env:
          TZ: Asia/Shanghai
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "yzdyzd13@gmail.com"
          git config --global user.name "Freddd13's Action"
          npm install hexo-cli -g
          npm install
          npm install hexo-deployer-git -save
          npm install hexo-blog-encrypt --save
          npm install hexo-generator-archive --save
          npm install hexo-generator-baidu-sitemap --save
          npm install hexo-generator-category --save
          npm install hexo-generator-feed --save
          npm install hexo-generator-index --save
          npm install hexo-generator-searchdb --save
          npm install hexo-generator-sitemap --save
          npm install hexo-generator-tag --save
          npm install hexo-renderer-ejs --save
          npm install hexo-renderer-marked --save
          npm install hexo-renderer-pug --save
          npm install hexo-renderer-stylus --save
          npm install hexo-tag-aplayer --save
          npm install hexo-tag-dplayer --save
          npm install hexo-wordcount --save
          npm install hexo-bilibili-bangumi --save
          npm install hexo-tag-bangumi --save
      - name: Hexo deploy
        run: |
          hexo clean
          hexo bangumi -u
          hexo d

